### ISSUE TITLE
在某些群禁止此功能

### ISSUE THREAD

**Issue by Relief156** [Moyuyanli/HuYanEconomy#18]
群里存在类似的机器人 会导致指令冲突）然后机器人会刷屏 希望可以增加一个某些群不启用功能

**Comment by Moyuyanli** [comment]
如果可以，我做成所有功能都需要权限可以吗？
反向黑名单不是很好实现。

**Comment by Relief156** [comment]
增加命令前缀也可以解决这个问题）让命令不一样即可
&nbsp;


遗忘之铭∝解脱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月9日(星期一) 下午3:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moyuyanli/HuYanEconomy] 在某些群禁止此功能 (Issue #18)














 
如果可以，我做成所有功能都需要权限可以吗？
 反向黑名单不是很好实现。

**Comment by Moyuyanli** [comment]
我也考虑了增加命令前缀问题，增加命令前缀是另外一个插件的功能。
那就看那个更好实现吧。

**Comment by Relief156** [comment]
我兴致冲冲的增加了命令前缀 然后发现“功能尚未实现”
&nbsp;


遗忘之铭∝解脱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月9日(星期一) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moyuyanli/HuYanEconomy] 在某些群禁止此功能 (Issue #18)














 
我也考虑了增加命令前缀问题，增加命令前缀是另外一个插件的功能。
 那就看那个更好实现吧。

**Comment by Moyuyanli** [comment]
之前是实现了的，但是刚刚接入了一个全局权限前置，那个里面我设计的时候没考虑到这个问题，所以现在得重新设计一下。

**Comment by Relief156** [comment]
如你之前所说 可以尝试 enable groups groupnumber1;groupnumber2&nbsp; 来启用群聊中的功能 可以默认全部&nbsp; 也可以 disable groups
&nbsp;


遗忘之铭∝解脱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月9日(星期一) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moyuyanli/HuYanEconomy] 在某些群禁止此功能 (Issue #18)














 
之前是实现了的，但是刚刚接入了一个全局权限前置，那个里面我设计的时候没考虑到这个问题，所以现在得重新设计一下。

**Comment by Moyuyanli** [comment]
现在对于功能的控制只有3个，分别是：抢劫，钓鱼和猜签。这三个默认是没有权限的。
无论是需要的黑名单权限机制，还是指令前缀机制，都得我的鉴权前置修改。

至于enable groups groupnumber1 这种指令，这个插件的指令功能点有点多，一刀切总是不太好的。

**Comment by Moyuyanli** [comment]
好了，两个都更新了，既可以控制前缀，也可以控制权限了

**Comment by Relief156** [comment]
太感谢了&nbsp;


遗忘之铭∝解脱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月12日(星期四) 下午3:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moyuyanli/HuYanEconomy] 在某些群禁止此功能 (Issue #18)














 
好了，两个都更新了，既可以控制前缀，也可以控制权限了
