### ISSUE TITLE
数据库异常大

### ISSUE THREAD

**Issue by Relief156** [Moyuyanli/HuYanEconomy#20]
![image](https://github.com/user-attachments/assets/b4688bb9-a333-47c8-a7b7-b34907ef86f5)
我这个玩意这么大 你有什么头绪吗哥哥 仅有此经济娱乐插件和该插件挂钩

**Comment by Moyuyanli** [comment]
这个是cssxsh的一个消息记录插件，但是他提供了一套数据库的api。

这个数据库大是因为，你所有的消息都被这个插件记录下来了，现在新版已经脱离了这个插件，但是壶言会话2还是使用的这个。

我记得貌似有个可以关闭消息记录的方法。
