### ISSUE TITLE
自定义称号

### ISSUE THREAD

**Issue by firefairy198** [Moyuyanli/HuYanEconomy#8]
让bot管理者可以编辑称号以及商店出售的金币，签到时可以显示出来。
该功能可以增加金币的用途。
如果可以，每个群可以设置不同的称号内容和出售金币。
如果可以，显示的称号颜色可以自行配置。

**Comment by Moyuyanli** [comment]
称号，颜色，能否购买，价格，显示都可以设置，但是不同群不一样做不到。
